//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieStreamTemplate.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.1.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MovieStreamTemplate.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        public static string Downloads {
            get {
                return ResourceManager.GetString("Downloads", resourceCulture);
            }
        }
        
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        public static string MovieGenres {
            get {
                return ResourceManager.GetString("MovieGenres", resourceCulture);
            }
        }
        
        public static string FeaturedMovies {
            get {
                return ResourceManager.GetString("FeaturedMovies", resourceCulture);
            }
        }
        
        public static string TrendingMovies {
            get {
                return ResourceManager.GetString("TrendingMovies", resourceCulture);
            }
        }
        
        public static string NewMovies {
            get {
                return ResourceManager.GetString("NewMovies", resourceCulture);
            }
        }
        
        public static string TopRatingMovies {
            get {
                return ResourceManager.GetString("TopRatingMovies", resourceCulture);
            }
        }
        
        public static string WelcomeLogIn {
            get {
                return ResourceManager.GetString("WelcomeLogIn", resourceCulture);
            }
        }
        
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        public static string LogInWithFacebook {
            get {
                return ResourceManager.GetString("LogInWithFacebook", resourceCulture);
            }
        }
        
        public static string LogInWithGoogle {
            get {
                return ResourceManager.GetString("LogInWithGoogle", resourceCulture);
            }
        }
        
        public static string DontHaveAccount {
            get {
                return ResourceManager.GetString("DontHaveAccount", resourceCulture);
            }
        }
        
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        public static string HelloSignUp {
            get {
                return ResourceManager.GetString("HelloSignUp", resourceCulture);
            }
        }
        
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        public static string ByClickingSignUp {
            get {
                return ResourceManager.GetString("ByClickingSignUp", resourceCulture);
            }
        }
        
        public static string TermsConditions {
            get {
                return ResourceManager.GetString("TermsConditions", resourceCulture);
            }
        }
        
        public static string AlreadyHaveAccount {
            get {
                return ResourceManager.GetString("AlreadyHaveAccount", resourceCulture);
            }
        }
        
        public static string ResetMyPassword {
            get {
                return ResourceManager.GetString("ResetMyPassword", resourceCulture);
            }
        }
        
        public static string PleaseTypeYourEmail {
            get {
                return ResourceManager.GetString("PleaseTypeYourEmail", resourceCulture);
            }
        }
        
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        public static string UpdatePlan {
            get {
                return ResourceManager.GetString("UpdatePlan", resourceCulture);
            }
        }
        
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        public static string Watchlist {
            get {
                return ResourceManager.GetString("Watchlist", resourceCulture);
            }
        }
        
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        public static string AccountDetails {
            get {
                return ResourceManager.GetString("AccountDetails", resourceCulture);
            }
        }
        
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        public static string EditPhotoTapped {
            get {
                return ResourceManager.GetString("EditPhotoTapped", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        public static string UseCellularData {
            get {
                return ResourceManager.GetString("UseCellularData", resourceCulture);
            }
        }
        
        public static string AllowNotifications {
            get {
                return ResourceManager.GetString("AllowNotifications", resourceCulture);
            }
        }
        
        public static string OnlyWifiWhenDownloading {
            get {
                return ResourceManager.GetString("OnlyWifiWhenDownloading", resourceCulture);
            }
        }
        
        public static string PrimaryProfileCantDelete {
            get {
                return ResourceManager.GetString("PrimaryProfileCantDelete", resourceCulture);
            }
        }
        
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        public static string ProfileDetails {
            get {
                return ResourceManager.GetString("ProfileDetails", resourceCulture);
            }
        }
        
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        public static string ShowOnlyMoviesForKids {
            get {
                return ResourceManager.GetString("ShowOnlyMoviesForKids", resourceCulture);
            }
        }
        
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        public static string DoYouWantToDelete {
            get {
                return ResourceManager.GetString("DoYouWantToDelete", resourceCulture);
            }
        }
        
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        public static string ChoosePlan {
            get {
                return ResourceManager.GetString("ChoosePlan", resourceCulture);
            }
        }
        
        public static string YouCanCancelAnyTime {
            get {
                return ResourceManager.GetString("YouCanCancelAnyTime", resourceCulture);
            }
        }
        
        public static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        public static string Standard {
            get {
                return ResourceManager.GetString("Standard", resourceCulture);
            }
        }
        
        public static string Premium {
            get {
                return ResourceManager.GetString("Premium", resourceCulture);
            }
        }
        
        public static string AnnularPrice {
            get {
                return ResourceManager.GetString("AnnularPrice", resourceCulture);
            }
        }
        
        public static string VideoQuality {
            get {
                return ResourceManager.GetString("VideoQuality", resourceCulture);
            }
        }
        
        public static string Good {
            get {
                return ResourceManager.GetString("Good", resourceCulture);
            }
        }
        
        public static string Better {
            get {
                return ResourceManager.GetString("Better", resourceCulture);
            }
        }
        
        public static string TheBest {
            get {
                return ResourceManager.GetString("TheBest", resourceCulture);
            }
        }
        
        public static string NumberOfDevices {
            get {
                return ResourceManager.GetString("NumberOfDevices", resourceCulture);
            }
        }
        
        public static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        public static string CardOwnersName {
            get {
                return ResourceManager.GetString("CardOwnersName", resourceCulture);
            }
        }
        
        public static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        public static string Cvc {
            get {
                return ResourceManager.GetString("Cvc", resourceCulture);
            }
        }
        
        public static string Checkout {
            get {
                return ResourceManager.GetString("Checkout", resourceCulture);
            }
        }
        
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        public static string Congratulations {
            get {
                return ResourceManager.GetString("Congratulations", resourceCulture);
            }
        }
        
        public static string YourPlanUpdated {
            get {
                return ResourceManager.GetString("YourPlanUpdated", resourceCulture);
            }
        }
        
        public static string Movies {
            get {
                return ResourceManager.GetString("Movies", resourceCulture);
            }
        }
        
        public static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        public static string DoYouWantToDeleteSearchHistory {
            get {
                return ResourceManager.GetString("DoYouWantToDeleteSearchHistory", resourceCulture);
            }
        }
        
        public static string DoYouWantToDeleteAllDownloadedMovies {
            get {
                return ResourceManager.GetString("DoYouWantToDeleteAllDownloadedMovies", resourceCulture);
            }
        }
        
        public static string DoYouWantToDeleteDownloadedMovie {
            get {
                return ResourceManager.GetString("DoYouWantToDeleteDownloadedMovie", resourceCulture);
            }
        }
        
        public static string PlayTapped {
            get {
                return ResourceManager.GetString("PlayTapped", resourceCulture);
            }
        }
        
        public static string NoItems {
            get {
                return ResourceManager.GetString("NoItems", resourceCulture);
            }
        }
        
        public static string Mins {
            get {
                return ResourceManager.GetString("Mins", resourceCulture);
            }
        }
        
        public static string Director {
            get {
                return ResourceManager.GetString("Director", resourceCulture);
            }
        }
        
        public static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        public static string CancelDownload {
            get {
                return ResourceManager.GetString("CancelDownload", resourceCulture);
            }
        }
        
        public static string DeleteDownload {
            get {
                return ResourceManager.GetString("DeleteDownload", resourceCulture);
            }
        }
        
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        public static string Downloaded {
            get {
                return ResourceManager.GetString("Downloaded", resourceCulture);
            }
        }
        
        public static string InWatchlist {
            get {
                return ResourceManager.GetString("InWatchlist", resourceCulture);
            }
        }
        
        public static string AddToWatchlist {
            get {
                return ResourceManager.GetString("AddToWatchlist", resourceCulture);
            }
        }
        
        public static string RemoveFromWatchlist {
            get {
                return ResourceManager.GetString("RemoveFromWatchlist", resourceCulture);
            }
        }
        
        public static string ShowReviews {
            get {
                return ResourceManager.GetString("ShowReviews", resourceCulture);
            }
        }
        
        public static string Reviews {
            get {
                return ResourceManager.GetString("Reviews", resourceCulture);
            }
        }
        
        public static string NewReview {
            get {
                return ResourceManager.GetString("NewReview", resourceCulture);
            }
        }
        
        public static string YourReview {
            get {
                return ResourceManager.GetString("YourReview", resourceCulture);
            }
        }
        
        public static string YourReviewOptional {
            get {
                return ResourceManager.GetString("YourReviewOptional", resourceCulture);
            }
        }
        
        public static string Question1 {
            get {
                return ResourceManager.GetString("Question1", resourceCulture);
            }
        }
        
        public static string Question2 {
            get {
                return ResourceManager.GetString("Question2", resourceCulture);
            }
        }
        
        public static string Question3 {
            get {
                return ResourceManager.GetString("Question3", resourceCulture);
            }
        }
        
        public static string Question4 {
            get {
                return ResourceManager.GetString("Question4", resourceCulture);
            }
        }
        
        public static string Question5 {
            get {
                return ResourceManager.GetString("Question5", resourceCulture);
            }
        }
        
        public static string Question6 {
            get {
                return ResourceManager.GetString("Question6", resourceCulture);
            }
        }
        
        public static string Question7 {
            get {
                return ResourceManager.GetString("Question7", resourceCulture);
            }
        }
        
        public static string Question8 {
            get {
                return ResourceManager.GetString("Question8", resourceCulture);
            }
        }
        
        public static string Question9 {
            get {
                return ResourceManager.GetString("Question9", resourceCulture);
            }
        }
        
        public static string Question10 {
            get {
                return ResourceManager.GetString("Question10", resourceCulture);
            }
        }
        
        public static string Answer1 {
            get {
                return ResourceManager.GetString("Answer1", resourceCulture);
            }
        }
        
        public static string Answer2 {
            get {
                return ResourceManager.GetString("Answer2", resourceCulture);
            }
        }
        
        public static string Answer3 {
            get {
                return ResourceManager.GetString("Answer3", resourceCulture);
            }
        }
        
        public static string Answer4 {
            get {
                return ResourceManager.GetString("Answer4", resourceCulture);
            }
        }
        
        public static string Answer5 {
            get {
                return ResourceManager.GetString("Answer5", resourceCulture);
            }
        }
        
        public static string Answer6 {
            get {
                return ResourceManager.GetString("Answer6", resourceCulture);
            }
        }
        
        public static string Answer7 {
            get {
                return ResourceManager.GetString("Answer7", resourceCulture);
            }
        }
        
        public static string Answer8 {
            get {
                return ResourceManager.GetString("Answer8", resourceCulture);
            }
        }
        
        public static string Answer9 {
            get {
                return ResourceManager.GetString("Answer9", resourceCulture);
            }
        }
        
        public static string Answer10 {
            get {
                return ResourceManager.GetString("Answer10", resourceCulture);
            }
        }
    }
}
